version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sip-royale
    environment:
      PUBLIC_URL: ${PUBLIC_URL}
    ports:
      - "25013:3000" # externalPort:internalPort